name: Tox tests

on: [push, pull_request]

jobs:
  py26:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev libssl1.0-dev
      - name: Add Python 2.6 repository
        run: sudo add-apt-repository ppa:deadsnakes/ppa
      - name: Install Python 2.6
        run: sudo apt-get install -y python2.6 python2.6-dev
      - name: Install setuptools
        run: sudo pip install --no-compile -t /usr/lib/python2.6/dist-packages setuptools==18.0 setuptools-scm==1.15.7 ordereddict argparse six
      - name: install pytest-py
        run: git clone https://github.com/pytest-dev/py && cd py && git checkout 1.4.33 && sudo python2.6 setup.py install && cd ../ && sudo rm -r py
      - name: Install pip
        run: curl -L https://github.com/pypa/get-pip/raw/main/public/2.7/get-pip.py -o get-pip.py && sudo python get-pip.py --no-setuptools
      - name: Install Python dependencies
        run: sudo pip install -r requirements-test-py26.txt -t /usr/lib/python2.6/dist-packages && sudo pip install .
      - name: Run tests
        run: sudo python2.6 -m pytest
  py27:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py27 -vv
  py37:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py37 -vv
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e black -vv
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e flake8 -vv
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs -vv
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update existing dependencies
        run: sudo apt-get update -y
      - name: Install system dependencies
        run: sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py37
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
